- name: Ensure packages installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - glusterfs-server
    - glusterfs-client

- name: Create needed directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ gluster.brick }}"
    - "{{ gluster.mount }}"

- name: Create volume
  gluster_volume:
    state: present
    name: "{{gluster.name }}"
    brick: "{{ gluster.brick }}"
    replicas: 2
    cluster: "{{ groups['web']|map('extract', hostvars, 'ansible_eth1')|map(attribute='ipv4')|map(attribute='address')|join(',') }}"
    host: "{{ inventory_hostname }}"
    force: yes
  run_once: true

- name: Mount volume for Drupal
  mount:
    name: "{{ gluster.mount }}"
    src: "{{ inventory_hostname }}:/{{ gluster.name }} "
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
